server:
  port: 8004
  max-http-request-header-size: 16KB

spring:
  # 数据库源配置
  datasource:
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    # 数据库连接池配置
    druid:
      # 连接器启动时创建的初始连接数
      initial-size: 1
      # 配置获取连接等待超时的时间
      max-wait: 60000
      max-active: 20
      # 最小
      min-idle: 3
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}
      timeout: 3000
      connectTimeout: 5000

#配置日志
logging:
  #此处存放日志的路径
  config: classpath:logback-spring.xml
  level:
    root: ${LOG_LEVEL}
  file:
    path: ${LOG_PATH}

# 企微消息配置
wechat:
  url: ${WECHAT_URL}
  agent-id: ${WECHAT_AGENT_ID}
  secret: ${WECHAT_SECRET}
  corp-id: ${WECHAT_CORP_ID}

# sceneDiy消息配置
scene-diy:
  url: ${SCENE_DIY_URL}
  api-key: ${SCENE_DIY_API_KEY}
  oa-url: ${SCENE_DIY_OA_URL}
  oa-password: ${SCENE_DIY_OA_PASSWORD}
  token: ${SCENE_DIY_TOKEN}
  smc-url: ${SCENE_DIY_SMC_URL}
  smc-ak: ${SCENE_DIY_SMC_AK}
  smc-sk: ${SCENE_DIY_SMC_SK}
  batch-service-id: ${SCENE_DIY_SERVICE_ID}
  env: ${SCENE_DIY_ENV}

