server:
  port: 8004
spring:
  # 数据库源配置
  datasource:
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.131.9.79:3306/bac_database?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: osp_user
    password: Aa123#@!
    # 数据库连接池配置
    druid:
      # 连接器启动时创建的初始连接数
      initial-size: 1
      # 配置获取连接等待超时的时间
      max-wait: 60000
      max-active: 20
      # 最小
      min-idle: 3
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
  data:
    redis:
      host: 120.92.70.222
      port: 6379
      password: dm_energy^#re(*p
      database: 6
      timeout: 3000
      connectTimeout: 5000
# 企微消息配置
wechat:
  url: https://qyapi.weixin.qq.com/cgi-bin
  agent-id: 1000260
  secret: i3t6P5Robmo9Y4D6Y9GmCFVO4yFUaot2a7RcVOB44BE
  corp-id: wwf98151b909eb3240

#配置日志
logging:
  #此处存放日志的路径
  config: classpath:logback-spring.xml
  level:
    root: debug
  file:
    path: '/Users/wangtian/Desktop/Work/workspace/message_log'

# sceneDiy消息配置
scene-diy:
  url: https://tenon-cmdb-test.sensetime.com
  api-key: 84a4ef7499eb43c2862cf3ec35d6eb2e5e2e
  oa-url: http://newoa-test.sensetime.com
  oa-password: uAx1uWX8ulfw
  token: 098f6bcd4621d373cade4e832627b4f6
  smc-url: https://tenon-cmdb-api-test.sensetime.com
  smc-ak: 00000000000000183819304608989259
  smc-sk: 0000000000000018381930460898926030460898
  batch-service-id: 16-189
  env: test






